### PR TITLE
Implementing Github Issues Fixes

### LINKED ISSUE #35: Investigate memory issue
**Describe the bug**
Sending images are taking too long because the backend is exceeding the soft memory limit, causing the instance to restart. The memory limit is currently 256MB, and we are taking 300-some MB for that one request.

**To Reproduce**
Happens any time the user presses the "send image" button during their turn

**Expected behavior**
Sending such a small query should not take up a lot of memory, and should almost be instant. We want to figure out if 200-something MB is the baseline (in which case we will expand the memory limit) or if we have a leak or inefficient usage somewhere.

**Screenshots**
Please attach results of profiling and memory monitoring below.

### LINKED ISSUE #44: One Firebase Initialization in Main
**Describe the bug**
We should have one Firebase initialization instead of multiple strewn throughout the code.

**Expected behavior**
If initialization fails, it can be handled before the request so the client doesn't lose data.

**Additional context**
- Firebase.init() should happen in Application.java
- projectID should be read in from a file instead of hard coded
- add getMapping("/") method back for pulse checking
- see if checking the firebase status is available to add

### LINKED ISSUE #48: Remove Start Game Email functionality
**Describe the bug**
Unneeded start game functionality.

### LINKED ISSUE #57: Merging Email & EmailType classes
**Describe the feature**
Improving the design, by merging the two email classes into one place

**Additional context**
- Make EmailType an enum subclass of email
- Switch case for createEmail method (default crashes server)
- private static final tempSubject & tempBody variables
- tempBody string formatting to incorporate gameID into final strings

### PR DESCRIPTION
**Pull request by AnthonyOdum**
### What is a quick description of the change?
- Increased memory size to address server restarting after requests
- Firebase is only initialized once in master, removing the need for multiple init methods
- Removed start game email functionality
- Merged the EmailType enum & Email classes

### Is this fixing an issue?

This closes #44 , closes #57, closes #35 & closes #48

### CODE REVIEW

File: api/src/main/java/com/google/sps/Application.java [hunk 1]
```diff
@@ -10,6 +10,17 @@
...
+    } catch (Exception e) {
+      throw new RuntimeException(e);
+    }
+
     SpringApplication.run(Application.class, args);
   }
+
+  @GetMapping("/")
+	public String pulseCheck() {
+		return "Server is alive!";
```
Comment (tomatocat) [inline api/src/main/java/com/google/sps/Application.java:24]: These appear to be tabs instead of spaces

File: api/src/main/java/com/google/sps/Application.java [hunk 2]
```diff
@@ -10,6 +10,17 @@
 
 public class Application {
   public static void main(String[] args) {
+    try {
+      Firebase.init();
+    } catch (Exception e) {
+      throw new RuntimeException(e);
```
Comment (tomatocat) [inline api/src/main/java/com/google/sps/Application.java:16]: What's the point of catching an exception just to throw it again

File: api/src/main/java/com/google/sps/SendNotifications.java [hunk 3]
```diff
@@ -95,46 +95,45 @@ public Email getNextRecipient(HttpServletRequest request, HttpServletResponse re
...
-    } else if (emailType == EmailType.TURN) {
-      Email player = getNextRecipient(request, response);
+        break;
+      case TURN:
+        Email player = getNextRecipient(request, response);
 
-      try {
-        Gmail service = ServiceCreation.createService();
+        try {
+          Gmail service = ServiceCreation.createService();
```
Comment (tomatocat) [inline api/src/main/java/com/google/sps/SendNotifications.java:123]: Is a new Gmail service required for every new email? Is it possible to create a static global Gmail service upon server start, just like Firebase?

File: api/src/main/java/com/google/sps/SendNotifications.java [hunk 4]
```diff
@@ -95,46 +95,45 @@ public Email getNextRecipient(HttpServletRequest request, HttpServletResponse re
   public void sendEmail(HttpServletRequest request, HttpServletResponse response)
       throws IOException, InterruptedException, ExecutionException {
 
-    Firebase.init();
-    Firestore db = FirestoreClient.getFirestore();
-
     EmailType emailType = EmailType.valueOf(request.getParameter("emailType").toUpperCase());
-    String gameID = request.getParameter("gameID");
     final String FROM = "pictophone.noreply@gmail.com";
```
Comment (tomatocat) [inline api/src/main/java/com/google/sps/SendNotifications.java:99]: could this be private

File: api/src/main/java/com/google/sps/Email.java [hunk 5]
```diff
@@ -46,4 +43,17 @@ public String getSubject(){
...
   }
+
+  static Email populateEmail(String gameID, String playerEmail, String playerName, EmailType emailType)
+    throws RuntimeException {
+
+    switch(emailType) {
+      case END:
+        return endGameEmail(gameID, new User(playerEmail, playerName));
+      default:
+        System.out.println("Invalid email type");
```
Comment (tomatocat) [inline api/src/main/java/com/google/sps/Email.java:54]: Don't really understand the point of emailType parameter if it can only call one email type. This is essentially calling endGameEmail with extra steps

**Comment by tomatocat** [comment]
FYI keywords need to be included to auto-close issues https://docs.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords

File: api/src/main/java/com/google/sps/Application.java (hunk 2 above)
Comment (AnthonyOdum) [reply api/src/main/java/com/google/sps/Application.java:16]: Is this not the same concept as wrapping exceptions?

Comment (tomatocat) [reply api/src/main/java/com/google/sps/Application.java:16]: Why do you need to wrap in this case

Comment (AnthonyOdum) [reply api/src/main/java/com/google/sps/Application.java:16]: I was under the impression when we talked that it was just better practice

Comment (tomatocat) [reply api/src/main/java/com/google/sps/Application.java:16]: Reason for rewrapping previously was because in terms of that API, the client sees it as an IOException since they are only caring about input-output. I don't think there is such thing as client api here

File: api/src/main/java/com/google/sps/Application.java [hunk 6]
```diff
@@ -10,6 +10,18 @@
 
 public class Application {
   public static void main(String[] args) {
+    try {
+      Firebase.init();
+      GmailService.init();
+    } catch (Exception e) {
+      e.printStackTrace();
```
Comment (tomatocat) [inline api/src/main/java/com/google/sps/Application.java:17]: What's the point of catching an exception here just to print a stack trace? this redundantly does the same thing as just letting it propagate

Comment (AnthonyOdum) [reply api/src/main/java/com/google/sps/Application.java:17]: what's your suggestion? My intention is to make sure the user knows what's happening, should I just print out the exception?

Comment (tomatocat) [reply api/src/main/java/com/google/sps/Application.java:17]: this does (negligibly) the same & is already built into java
https://github.com/googleinterns/step119-2020/pull/47#discussion_r458966849

Comment (AnthonyOdum) [reply api/src/main/java/com/google/sps/Application.java:17]: Considering that this is the first server being booted up, wouldn't this being the first method that's called? Wouldn't this make it so that the Exception propogated to the bottom of the call stack unchecked?

Comment (tomatocat) [reply api/src/main/java/com/google/sps/Application.java:17]: It will propagate up, which prints out the stack trace. The same behavior as e.printStackTrace but without writing extra code. Propagating a checked exception does not make it unchecked (converting into RuntimeException does).

Comment (AnthonyOdum) [reply api/src/main/java/com/google/sps/Application.java:17]: I used the wrong pharsing, what I mean is when the exception is propagated upwards, it's being propagated toward somewhere that handles the exception, correct? if so, since this is the first method being called, where is the exception being handled, if not in this catch block. My current assumption is that you're suggesting leave the catch block empty so that the exception can be moved elsewhere, but I can't really make sense of why

Comment (tomatocat) [reply api/src/main/java/com/google/sps/Application.java:17]: There is a [default exception handler](https://stackoverflow.com/questions/27664104/how-default-exception-handler-work) in the JVM. Probably if the firebase or gmail init fail, we don't want the program to keep running. So we don't want to silently print and continue.

Comment (AnthonyOdum) [reply api/src/main/java/com/google/sps/Application.java]: okay cool, I understand. going to push now

File: api/src/main/java/com/google/sps/Application.java [hunk 7]
```diff
@@ -10,6 +10,18 @@
 
 public class Application {
   public static void main(String[] args) {
+    try {
+      Firebase.init();
+      GmailService.init();
+    } catch (Exception e) {
+      
+    }
```
Comment (pl98) [inline api/src/main/java/com/google/sps/Application.java:18]: Nothing is happening in this catch block.

Comment (AnthonyOdum) [reply api/src/main/java/com/google/sps/Application.java:18]: jeremy and i went through this earlier, he suggested the propagation similar to in your PR, however since this is the main method there's nothing to throw, so I figured the [default exception handler](https://stackoverflow.com/questions/27664104/how-default-exception-handler-work) would handle the caught exception. Am i understanding that correctly?
