### PR TITLE
fix small bugs

### LINKED ISSUE #34: Various small frontend bugs
**Describe the bug**
- [x] completed games are not rendered in the dashboard cards (probable due to index OOB error)
- [x] game page displays game ID instead of game name
- [x] email verification should link to deployment website instead of localhost
- [x] game page should have a button to copy game invite id or link
- [x] after game creation, redirect to that game's page instead of the dashboard
- [x] after game join, redirect to that game's page instead of the dashboard
- [x] make sure users can't join the same game twice
- [x] make sure users can't join games that have already ended

**Screenshots**
None, feel free to add

**Additional context**
Mostly from Tony's email after MVP presentation. Feel free to move into separate individual issues if anything seems too big to be compiled here.

### PR DESCRIPTION
**Pull request by tomatocat**
- Fixes #34 
- Add some autocomplete form elements for better accessibility

### Screenshots
Screenshot 2020-07-21 at 6 03 48 PM

### CODE REVIEW

File: client/src/components/SignIn/index.js [hunk 1]
```diff
@@ -59,13 +59,15 @@ class SignInFormBase extends Component {
         <input
           name="email"
           value={email}
+          autoComplete="username"
```
Comment (pl98) [inline client/src/components/SignIn/index.js:62]: What is the purpose of autocomplete? Doesn't the webpage already do this?

Comment (tomatocat) [reply client/src/components/SignIn/index.js:62]: The most recent version of Chrome does, but for increased accessibility across different platforms, the autoComplete attribute helps browsers identify what types they are (it was just a console warning I got while running React so I fixed it, but  [https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete](here's more info))

Comment (pl98) [reply client/src/components/SignIn/index.js:62]: Interesting, good to know!
